### ISSUE TITLE
RTL not working in free version

### ISSUE THREAD

**Issue by niloofaradibi** [themeselection/sneat-vuetify-vuejs-admin-template-free#1]
### Steps to reproduce

i added isRtl true in file src/plugins/vuetify/theme.js but it didnt work ..why ?
can support rtl really ?

### What is expected?

theme become RTL

### What is actually happening?

stay LTR

**Comment by yagnikvamja** [comment]
Hello @niloofaradibi ,

Thank you for contacting us.

The RTL(Right-to-left) feature is included in the pro version of our template. In the free version, you have to setup manually.

Please feel free to check out our Sneat Vuejs Pro version: https://themeselection.com/item/sneat-vuetify-vuejs-admin-template/
